### PR TITLE
Adding "Omada"

### PR DESCRIPTION
**Pull request by mehiel**
TP-Link's Omada SDN project. See https://www.tp-link.com/en/omada-sdn/

### CODE REVIEW

**Review by gsaslis — APPROVED** [review]
amazing - thanks for contributing @mehiel ! 👏

**Comment by gsaslis** [comment]
@mehiel after #12 , I'm trying to check if we have any **services** that are offered under a greek name (rather than software projects). 

Do you happen to know if "Omada" is a service or a software project?

**Comment by mehiel** [comment]
> Do you happen to know if "Omada" is a service or a software project?

It's definitely a service! 
There is a software platform in its core part of course but it's the whole offering named "Omada".

**Comment by gsaslis** [comment]
Removed in c71cbcd8ec0febcd5ce3f30cf6bd579d85386b4c

**Pull request merged**
